packages:
  - .

allowBuilds:
  es5-ext: true
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - es5-ext

overrides:
  '@melt-ui/svelte': ^0.86.6
  bits-ui: ^2.17.3
  cookie: ^1.0.2
  valibot: ^1.3.1
  esbuild: ^0.28.0
